plugins {
    id 'java'
}

version = "${mod_version}"
group   = maven_group
base { archivesName = "weather-structure-mod-paper" }

dependencies {
    compileOnly "io.papermc.paper:paper-api:${paper_api}"

    implementation project(':common')
}

def targetJava = 25
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release  = targetJava
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("${rootProject.projectDir}/LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }
    from(project(':common').sourceSets.main.output)
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("plugin.yml") { expand "version": project.version }
}
